(function () {
  'use strict';

  const RADIUS_KEY = 'safeboat.anchor.radius';
  const CONFIRM_KEY = 'safeboat.mob.confirmation';
  const MIN_RADIUS = 20;
  const MAX_RADIUS = 300;
  const messages = {
    'sr-RS': { CAUTION: 'Pažnja. Približavate se granici sidrenja.', ALARM: 'Alarm sidra! Plovilo se udaljilo izvan zadate zone.', GPS_LOST: 'Upozorenje. GPS signal za nadzor sidra je izgubljen.', mobStart: 'Čovek u vodi! MOB tačka je sačuvana. Odmah započnite povratak.', mobRepeat: (d, b) => `MOB je aktivan. Udaljenost ${d} metara. Kurs ${b} stepeni.`, mobNear: 'U neposrednoj ste blizini MOB tačke.', mobResolved: 'MOB događaj je označen kao rešen.' },
    'en-US': { CAUTION: 'Caution. You are approaching the anchor watch boundary.', ALARM: 'Anchor alarm! The vessel has moved outside the set zone.', GPS_LOST: 'Warning. The GPS signal for anchor watch has been lost.', mobStart: 'Man overboard! The MOB point has been saved. Begin your return immediately.', mobRepeat: (d, b) => `MOB is active. Distance ${d} metres. Bearing ${b} degrees.`, mobNear: 'You are very close to the MOB point.', mobResolved: 'The MOB incident has been marked resolved.' },
    'el-GR': { CAUTION: 'Προσοχή. Πλησιάζετε το όριο επιτήρησης άγκυρας.', ALARM: 'Συναγερμός άγκυρας! Το σκάφος βγήκε από την καθορισμένη ζώνη.', GPS_LOST: 'Προειδοποίηση. Το σήμα GPS για την επιτήρηση άγκυρας χάθηκε.', mobStart: 'Άνθρωπος στη θάλασσα! Το σημείο MOB αποθηκεύτηκε. Ξεκινήστε αμέσως επιστροφή.', mobRepeat: (d, b) => `Το MOB είναι ενεργό. Απόσταση ${d} μέτρα. Πορεία ${b} μοίρες.`, mobNear: 'Βρίσκεστε πολύ κοντά στο σημείο MOB.', mobResolved: 'Το συμβάν MOB σημειώθηκε ως επιλυμένο.' }
  };
  const statusNames = { INACTIVE: 'NEAKTIVAN', SAFE: 'BEZBEDNO', CAUTION: 'OPREZ', ALARM: 'ALARM', GPS_POOR: 'SLAB GPS', GPS_LOST: 'GPS IZGUBLJEN' };
  const anchor = { active: false, anchorLatitude: null, anchorLongitude: null, radiusMeters: readRadius(), startedAt: null, currentDistanceMeters: null, maxDistanceMeters: 0, status: 'INACTIVE', lastPosition: null, alertCount: 0 };
  const mob = { active: false, resolved: false, activatedAt: null, latitude: null, longitude: null, activationAccuracy: null, currentDistanceMeters: null, bearingToMOB: null, elapsedSeconds: 0, lastPosition: null };
  let latest = null; let staleTimer = null; let clockTimer = null; let anchorLayers = null; let mobLayers = null;
  let outsideFixes = 0; let insideFixes = 0; let nearAnnounced = false; let lastMOBAnnouncement = 0;
  const lastAlerts = { CAUTION: 0, ALARM: 0, GPS_LOST: 0 }; let previousAlertLevel = 'SAFE';
  const ui = {};

  function stored(key) { try { return localStorage.getItem(key); } catch (_) { return null; } }
  function store(key, value) { try { localStorage.setItem(key, value); } catch (_) { /* settings are optional */ } }
  function readRadius() { const value = Number(stored(RADIUS_KEY)); return Number.isFinite(value) && value >= MIN_RADIUS && value <= MAX_RADIUS ? value : 50; }
  function positionData(position) {
    if (!position || !position.coords) return null;
    const latitude = Number(position.coords.latitude); const longitude = Number(position.coords.longitude); const timestamp = Number(position.timestamp);
    if (!Number.isFinite(latitude) || !Number.isFinite(longitude) || latitude < -90 || latitude > 90 || longitude < -180 || longitude > 180 || !Number.isFinite(timestamp)) return null;
    return { latitude, longitude, accuracy: Number(position.coords.accuracy), timestamp };
  }
  function radians(value) { return value * Math.PI / 180; }
  function distance(aLat, aLon, bLat, bLon) { const dLat = radians(bLat - aLat); const dLon = radians(bLon - aLon); const q = Math.sin(dLat / 2) ** 2 + Math.cos(radians(aLat)) * Math.cos(radians(bLat)) * Math.sin(dLon / 2) ** 2; return 6371000 * 2 * Math.atan2(Math.sqrt(q), Math.sqrt(1 - q)); }
  function bearing(aLat, aLon, bLat, bLon) { const dLon = radians(bLon - aLon); const y = Math.sin(dLon) * Math.cos(radians(bLat)); const x = Math.cos(radians(aLat)) * Math.sin(radians(bLat)) - Math.sin(radians(aLat)) * Math.cos(radians(bLat)) * Math.cos(dLon); return (Math.atan2(y, x) * 180 / Math.PI + 360) % 360; }
  function notify(text) { const element = document.querySelector('#message'); if (!element) { window.alert(text); return; } element.textContent = text; element.classList.add('show'); window.setTimeout(() => element.classList.remove('show'), 5000); }
  function language() { return window.SafeBoatVoice && window.SafeBoatVoice.getLanguage ? window.SafeBoatVoice.getLanguage() : 'sr-RS'; }
  function speak(text, priority) { if (window.SafeBoatVoice && window.SafeBoatVoice.announceEmergency) return window.SafeBoatVoice.announceEmergency(text, priority); fallback(priority); return false; }
  function fallback(kind) { const patterns = { CAUTION: [250, 150, 250], ALARM: [700, 200, 700, 200, 900], GPS_LOST: [400, 200, 400], MOB: [800, 150, 800, 150, 1000] }; if (navigator.vibrate) navigator.vibrate(patterns[kind] || patterns.MOB); try { const Audio = window.AudioContext || window.webkitAudioContext; if (!Audio) return; const context = new Audio(); const frequencies = kind === 'GPS_LOST' ? [330, 280] : kind === 'CAUTION' ? [620, 620] : [880, 660, 880]; frequencies.forEach((frequency, index) => { const osc = context.createOscillator(); const gain = context.createGain(); const start = context.currentTime + index * .28; osc.frequency.value = frequency; gain.gain.setValueAtTime(.18, start); gain.gain.exponentialRampToValueAtTime(.001, start + .18); osc.connect(gain).connect(context.destination); osc.start(start); osc.stop(start + .2); }); } catch (_) { /* visible warning remains */ } }
  function tripEvent(event) { try { if (window.SafeBoatTrip && window.SafeBoatTrip.addEvent) window.SafeBoatTrip.addEvent(event); } catch (_) { /* recorder is optional */ } }
  function emit(name, detail) { window.dispatchEvent(new CustomEvent(name, { detail })); }
  function mapObject() { return window.SafeBoatMap && window.SafeBoatMap.map && window.L ? window.SafeBoatMap.map : null; }
  function anchorColor() { return ({ SAFE: '#20b966', CAUTION: '#ed8b24', ALARM: '#dc3545', GPS_POOR: '#e7c42f', GPS_LOST: '#7c2020' })[anchor.status] || '#879aa4'; }
  function drawAnchor(position) { const map = mapObject(); if (!map) return; if (!anchorLayers) anchorLayers = L.layerGroup().addTo(map); anchorLayers.clearLayers(); const point = [anchor.anchorLatitude, anchor.anchorLongitude]; L.marker(point, { icon: L.divIcon({ className: 'anchor-marker', html: '⚓', iconSize: [34, 34], iconAnchor: [17, 17] }) }).bindPopup('Anchor Watch tačka').addTo(anchorLayers); L.circle(point, { radius: anchor.radiusMeters, color: anchorColor(), weight: 3, fillOpacity: .08 }).addTo(anchorLayers); if (position) L.polyline([point, [position.latitude, position.longitude]], { color: anchorColor(), weight: 3, dashArray: '6 7', interactive: false }).addTo(anchorLayers); }
  function drawMOB(position) { const map = mapObject(); if (!map || !mob.active) return; if (!mobLayers) mobLayers = L.layerGroup().addTo(map); mobLayers.clearLayers(); const point = [mob.latitude, mob.longitude]; L.marker(point, { zIndexOffset: 2000, icon: L.divIcon({ className: 'mob-marker', html: '🆘', iconSize: [48, 48], iconAnchor: [24, 24] }) }).bindPopup('MOB tačka').addTo(mobLayers); if (position) L.polyline([[position.latitude, position.longitude], point], { color: '#e2192d', weight: 6, opacity: .95, interactive: false }).addTo(mobLayers).bringToFront(); }
  function setAnchorRadius(value) { const radius = Math.round(Number(value)); if (!Number.isFinite(radius) || radius < MIN_RADIUS || radius > MAX_RADIUS) return false; anchor.radiusMeters = radius; store(RADIUS_KEY, radius); if (ui.radius) ui.radius.value = radius; if (ui.settingsRadius) ui.settingsRadius.value = radius; render(); if (anchor.active) drawAnchor(anchor.lastPosition); return true; }
  function render() { if (!ui.anchorPanel) return; ui.anchorPanel.dataset.status = anchor.status; ui.anchorStatus.textContent = statusNames[anchor.status]; ui.radiusValue.textContent = `${anchor.radiusMeters} m`; ui.anchorDistance.textContent = Number.isFinite(anchor.currentDistanceMeters) ? `${Math.round(anchor.currentDistanceMeters)} m` : '—'; ui.anchorMaximum.textContent = anchor.active ? `${Math.round(anchor.maxDistanceMeters)} m` : '—'; ui.anchorAccuracy.textContent = anchor.lastPosition && Number.isFinite(anchor.lastPosition.accuracy) ? `±${Math.round(anchor.lastPosition.accuracy)} m` : '—'; ui.anchorElapsed.textContent = anchor.startedAt ? formatTime((Date.now() - anchor.startedAt) / 1000) : '00:00'; ui.start.disabled = anchor.active; ui.stop.disabled = !anchor.active;
    ui.mobCard.hidden = !mob.active; if (mob.active) { ui.mobDistance.textContent = Number.isFinite(mob.currentDistanceMeters) ? `${Math.round(mob.currentDistanceMeters)} m` : '—'; ui.mobBearing.textContent = Number.isFinite(mob.bearingToMOB) ? `${Math.round(mob.bearingToMOB)}°` : '—'; ui.mobElapsed.textContent = formatTime(mob.elapsedSeconds); ui.mobAccuracy.textContent = latest && Date.now() - latest.timestamp <= 20000 && Number.isFinite(latest.accuracy) ? `±${Math.round(latest.accuracy)} m` : 'GPS signal nije ažuriran'; ui.mobProximity.textContent = mob.currentDistanceMeters <= 20 ? 'U neposrednoj blizini MOB tačke' : ''; }
  }
  function formatTime(seconds) { const total = Math.max(0, Math.floor(seconds)); return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`; }
  function alertAnchor(level, position, force) { const now = Date.now(); const gaps = { CAUTION: 60000, ALARM: 15000, GPS_LOST: 30000 }; const seriousness = { SAFE: 0, CAUTION: 1, ALARM: 2, GPS_LOST: 3 }; if (!force && seriousness[level] <= seriousness[previousAlertLevel] && now - lastAlerts[level] < gaps[level]) return; lastAlerts[level] = now; previousAlertLevel = level; anchor.alertCount += 1; const detail = { level, distanceMeters: anchor.currentDistanceMeters, radiusMeters: anchor.radiusMeters, accuracy: position && position.accuracy, latitude: position ? position.latitude : anchor.anchorLatitude, longitude: position ? position.longitude : anchor.anchorLongitude, timestamp: now }; emit('safeboat:anchor-alert', detail); tripEvent({ type: 'ANCHOR_ALERT', level, distanceMeters: detail.distanceMeters, radiusMeters: detail.radiusMeters, timestamp: now, latitude: detail.latitude, longitude: detail.longitude }); speak(messages[language()]?.[level] || messages['sr-RS'][level], level); }
  function updateAnchor(position) { if (!anchor.active) return; anchor.lastPosition = position; if (Number.isFinite(position.accuracy) && position.accuracy > 50) { anchor.status = 'GPS_POOR'; outsideFixes = 0; insideFixes = 0; drawAnchor(position); render(); return; } const d = distance(anchor.anchorLatitude, anchor.anchorLongitude, position.latitude, position.longitude); anchor.currentDistanceMeters = d; anchor.maxDistanceMeters = Math.max(anchor.maxDistanceMeters, d);
    if (d > anchor.radiusMeters) { outsideFixes += 1; insideFixes = 0; if (anchor.status === 'ALARM' || outsideFixes >= 2) anchor.status = 'ALARM'; else anchor.status = 'CAUTION'; } else if (anchor.status === 'ALARM') { outsideFixes = 0; if (d <= anchor.radiusMeters * .8) insideFixes += 1; else insideFixes = 0; if (insideFixes >= 2) anchor.status = d <= anchor.radiusMeters * .7 ? 'SAFE' : 'CAUTION'; } else { outsideFixes = 0; anchor.status = d <= anchor.radiusMeters * .7 ? 'SAFE' : 'CAUTION'; }
    if (anchor.status === 'SAFE') { lastAlerts.CAUTION = 0; lastAlerts.ALARM = 0; lastAlerts.GPS_LOST = 0; previousAlertLevel = 'SAFE'; } else if (['CAUTION', 'ALARM'].includes(anchor.status)) alertAnchor(anchor.status, position); drawAnchor(position); render(); }
  function startAnchorWatch() { if (!latest) { notify('Pokrenite GPS pre uključivanja Anchor Watch funkcije.'); return false; } if (Date.now() - latest.timestamp > 20000) { notify('GPS pozicija nije dovoljno sveža za Anchor Watch.'); return false; } if (!Number.isFinite(latest.accuracy) || latest.accuracy > 30) { notify('GPS preciznost mora biti 30 metara ili bolja.'); return false; } Object.assign(anchor, { active: true, anchorLatitude: latest.latitude, anchorLongitude: latest.longitude, startedAt: Date.now(), currentDistanceMeters: 0, maxDistanceMeters: 0, status: 'SAFE', lastPosition: latest, alertCount: 0 }); outsideFixes = 0; insideFixes = 0; previousAlertLevel = 'SAFE'; Object.keys(lastAlerts).forEach(key => { lastAlerts[key] = 0; }); drawAnchor(latest); startTimers(); render(); emit('safeboat:anchor-started', { latitude: latest.latitude, longitude: latest.longitude, radiusMeters: anchor.radiusMeters, accuracy: latest.accuracy, timestamp: anchor.startedAt }); return true; }
  function stopAnchorWatch() { anchor.active = false; anchor.status = 'INACTIVE'; anchor.startedAt = null; anchor.currentDistanceMeters = null; if (anchorLayers) { anchorLayers.clearLayers(); const map = mapObject(); if (map) map.removeLayer(anchorLayers); anchorLayers = null; } stopTimersIfIdle(); render(); return true; }
  function staleCheck() { const now = Date.now(); if (anchor.active && (!latest || now - latest.timestamp > 20000)) { anchor.status = 'GPS_LOST'; alertAnchor('GPS_LOST', latest); drawAnchor(latest); render(); } if (mob.active) { mob.elapsedSeconds = Math.floor((now - mob.activatedAt) / 1000); if (now - lastMOBAnnouncement >= 30000 && latest && now - latest.timestamp <= 20000) { lastMOBAnnouncement = now; speak(messages[language()].mobRepeat(Math.round(mob.currentDistanceMeters || 0), Math.round(mob.bearingToMOB || 0)), 'MOB'); } render(); } }
  function startTimers() { if (!staleTimer) staleTimer = window.setInterval(staleCheck, 5000); if (!clockTimer) clockTimer = window.setInterval(render, 1000); }
  function stopTimersIfIdle() { if (anchor.active || mob.active) return; if (staleTimer) window.clearInterval(staleTimer); if (clockTimer) window.clearInterval(clockTimer); staleTimer = null; clockTimer = null; }
  function updatePosition(position) { const value = positionData(position); if (!value) return false; latest = value; if (anchor.active) updateAnchor(value); if (mob.active) { mob.lastPosition = value; mob.currentDistanceMeters = distance(value.latitude, value.longitude, mob.latitude, mob.longitude); mob.bearingToMOB = bearing(value.latitude, value.longitude, mob.latitude, mob.longitude); if (mob.currentDistanceMeters <= 20 && !nearAnnounced) { nearAnnounced = true; speak(messages[language()].mobNear, 'MOB'); } else if (mob.currentDistanceMeters > 25) nearAnnounced = false; drawMOB(value); render(); } return true; }
  function activateMOB() { if (!latest || Date.now() - latest.timestamp > 15000) { notify('Nema dovoljno sveže GPS pozicije za čuvanje MOB tačke.'); return false; } const time = Date.now(); Object.assign(mob, { active: true, resolved: false, activatedAt: time, latitude: latest.latitude, longitude: latest.longitude, activationAccuracy: latest.accuracy, currentDistanceMeters: 0, bearingToMOB: 0, elapsedSeconds: 0, lastPosition: latest }); nearAnnounced = false; lastMOBAnnouncement = time; drawMOB(latest); startTimers(); render(); emit('safeboat:mob-activated', { latitude: mob.latitude, longitude: mob.longitude, accuracy: mob.activationAccuracy, timestamp: time }); tripEvent({ type: 'MOB_ACTIVATED', timestamp: time, latitude: mob.latitude, longitude: mob.longitude, accuracy: mob.activationAccuracy }); speak(messages[language()].mobStart, 'MOB'); return true; }
  function finishMOB(resolved) { if (!mob.active) return false; const timestamp = Date.now(); mob.active = false; mob.resolved = resolved; if (resolved) mob.resolvedAt = timestamp; const suffix = resolved ? 'resolved' : 'cancelled'; emit(`safeboat:mob-${suffix}`, { latitude: mob.latitude, longitude: mob.longitude, timestamp }); tripEvent({ type: resolved ? 'MOB_RESOLVED' : 'MOB_CANCELLED', timestamp, latitude: mob.latitude, longitude: mob.longitude }); if (resolved) speak(messages[language()].mobResolved, 'MOB'); if (window.SafeBoatVoice && window.SafeBoatVoice.setEmergencyActive) window.SafeBoatVoice.setEmergencyActive(false); if (mobLayers) { mobLayers.clearLayers(); const map = mapObject(); if (map) map.removeLayer(mobLayers); mobLayers = null; } stopTimersIfIdle(); render(); return true; }
  function resolveMOB() { if (!mob.active || !window.confirm('Označiti MOB događaj kao rešen?')) return false; return finishMOB(true); }
  function cancelMOB() { if (!mob.active || !window.confirm('Otkažite samo ako je MOB aktiviran slučajno. Nastaviti?')) return false; return finishMOB(false); }
  function testAnchorAlert() { alertAnchor('ALARM', latest || { latitude: 0, longitude: 0, accuracy: null }, true); }
  function testMOB() { notify('MOB test: kontrola je dostupna. Prava MOB tačka nije napravljena.'); fallback('MOB'); }
  function openCallDialog() { ui.coordinates.textContent = `Latitude: ${mob.latitude.toFixed(6)}\nLongitude: ${mob.longitude.toFixed(6)}`; ui.callDialog.showModal ? ui.callDialog.showModal() : ui.callDialog.setAttribute('open', ''); }
  async function copyCoordinates() { const text = ui.coordinates.textContent; try { if (!navigator.clipboard || !navigator.clipboard.writeText) throw new Error(); await navigator.clipboard.writeText(text); ui.copyStatus.textContent = 'Koordinate su kopirane.'; } catch (_) { const selection = window.getSelection(); const range = document.createRange(); range.selectNodeContents(ui.coordinates); selection.removeAllRanges(); selection.addRange(range); ui.copyStatus.textContent = 'Automatsko kopiranje nije uspelo. Koordinate su označene za ručno kopiranje.'; } }
  function init() { Object.assign(ui, { anchorPanel: document.querySelector('#anchor-panel'), anchorStatus: document.querySelector('#anchor-status'), radius: document.querySelector('#anchor-radius'), settingsRadius: document.querySelector('#settings-anchor-radius'), radiusValue: document.querySelector('#anchor-radius-value'), anchorDistance: document.querySelector('#anchor-distance'), anchorMaximum: document.querySelector('#anchor-maximum'), anchorAccuracy: document.querySelector('#anchor-accuracy'), anchorElapsed: document.querySelector('#anchor-elapsed'), start: document.querySelector('#anchor-start'), stop: document.querySelector('#anchor-stop'), mobCard: document.querySelector('#mob-card'), mobDistance: document.querySelector('#mob-distance'), mobBearing: document.querySelector('#mob-bearing'), mobElapsed: document.querySelector('#mob-elapsed'), mobAccuracy: document.querySelector('#mob-accuracy'), mobProximity: document.querySelector('#mob-proximity'), callDialog: document.querySelector('#emergency-call-dialog'), coordinates: document.querySelector('#mob-coordinates'), copyStatus: document.querySelector('#copy-status') });
    if (!ui.anchorPanel) return window.SafeBoatEmergency; ui.radius.value = anchor.radiusMeters; ui.settingsRadius.value = anchor.radiusMeters; ui.start.addEventListener('click', startAnchorWatch); ui.stop.addEventListener('click', stopAnchorWatch); document.querySelector('#anchor-test').addEventListener('click', testAnchorAlert); ui.radius.addEventListener('input', event => setAnchorRadius(event.target.value)); ui.settingsRadius.addEventListener('change', event => setAnchorRadius(event.target.value));
    const confirmation = document.querySelector('#mob-confirmation'); confirmation.checked = stored(CONFIRM_KEY) !== 'false'; confirmation.addEventListener('change', () => store(CONFIRM_KEY, String(confirmation.checked)));
    const activate = document.querySelector('#mob-activate'); let hold = null; const clear = () => { if (hold) window.clearTimeout(hold); hold = null; activate.classList.remove('holding'); }; const begin = () => { clear(); activate.classList.add('holding'); hold = window.setTimeout(() => { clear(); if (window.confirm('Aktivirati hitni režim ČOVEK U VODI?')) activateMOB(); }, 1500); }; activate.addEventListener('pointerdown', begin); activate.addEventListener('pointerup', clear); activate.addEventListener('pointercancel', clear); activate.addEventListener('pointerleave', clear); activate.addEventListener('keydown', event => { if ((event.key === 'Enter' || event.key === ' ') && !event.repeat) { event.preventDefault(); begin(); } }); activate.addEventListener('keyup', clear);
    document.querySelector('#mob-center').addEventListener('click', () => { const map = mapObject(); if (map && mob.active) map.setView([mob.latitude, mob.longitude], Math.max(map.getZoom(), 17)); }); document.querySelector('#mob-help-open').addEventListener('click', openCallDialog); document.querySelector('#mob-resolve').addEventListener('click', resolveMOB); document.querySelector('#mob-cancel').addEventListener('click', cancelMOB); document.querySelector('#copy-coordinates').addEventListener('click', copyCoordinates); const close = () => ui.callDialog.close ? ui.callDialog.close() : ui.callDialog.removeAttribute('open'); document.querySelector('#emergency-call-close').addEventListener('click', close); document.querySelector('#emergency-call-close-x').addEventListener('click', close); render(); return window.SafeBoatEmergency; }
  function getAnchorState() { return Object.assign({}, anchor); } function getMOBState() { return Object.assign({}, mob); }
  window.SafeBoatEmergency = { init, updatePosition, startAnchorWatch, stopAnchorWatch, isAnchorWatchActive: () => anchor.active, getAnchorState, setAnchorRadius, activateMOB, cancelMOB, resolveMOB, isMOBActive: () => mob.active, getMOBState, testAnchorAlert, testMOB };
}());
